apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-filesystem-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: pvc-filesystem-static
  storageClassName: ""
