apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  flexVolume:
    driver: diamanti.com/nfs
    fsType: ext4
    options:
      name: nfs-pv
      type: nfs
      server: 172.16.0.25
      path: "/dws_nas_scratch/backupdir"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  volumeName: nfs-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  annotations:
    diamanti.com/endpoint: none
spec:
  containers:
  - image: centos:7.5.1804
    command: ["tar"]
    args:
      - "-xvpz"
      - "--file=/backup-dir/tar-backup-default-test-pvc-1541048551.tar.gz"
      - "--strip-components=1"
      - "-C"
      - "/data"
      - "--numeric-owner"
    name: tar-backup
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /data
      name: restore-vol
    - mountPath: /backup-dir
      name: backup-vol
  restartPolicy: OnFailure
  volumes:
  - name: restore-vol
    persistentVolumeClaim:
      claimName: restore-test-pvc
  - name: backup-vol
    persistentVolumeClaim:
      claimName: nfs-pvc
