apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-12
  name: mysql-12
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-12
  template:
    metadata:
      annotations:
        diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
      labels:
        app: mysql-12
    spec:
      containers:
      - args:
        - --datadir=/var/lib/mysql/mysql
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: mysql
        imagePullPolicy: IfNotPresent
        name: mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-1
        persistentVolumeClaim:
          claimName: mysql-sample-claim
