apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: diamanti.com/iscsi
    fsType: ext4
    readOnly: true
    options:
      name: iscsi-vol
      type: iscsi
      targetPortal: 172.16.176.251:3260
      portals: '["172.16.176.250:3260"]'
      iqn: iqn.1991-05.com.microsoft:win-t8lt532iapj-isgt-target
      lun: "0"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc
spec:
  volumeName: iscsi-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
