apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  flexVolume:
    driver: diamanti.com/nfs
    fsType: ext4
    options:
      name: nfs-pv
      type: nfs
      server: 172.16.240.16
      path: "/exports"
      mountOptions: "nfsvers=3,soft"
      route: "172.16.244.0/24,172.16.240.17"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  volumeName: nfs-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
