apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
  storageClassName: ""
  volumeName: static-volume
