apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: static-vol
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Gi
    flexVolume:
      driver: diamanti.com/volume
      fsType: xfs
      options:
        name: static-vol
        perfTier: high
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: static-pv-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100G
    storageClassName: ""
    volumeName: static-vol
kind: List
metadata: {}
