apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-dynamic
spec:
  storageClassName: best-effort
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      