apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-block-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Block
  volumeName: pvc-block-static
  storageClassName: ""
