apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: volume-images-pv-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: high
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: volume-1-pv-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 400Gi
    storageClassName: kvm-data-high
kind: List
metadata: {}
