---
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: image-repo
  spec:
    template:
      metadata:
        labels:
          diamanti.com/app: kvm-nginx
      spec:
        hostNetwork: true
        containers:
        - image: nginx:1.13
          imagePullPolicy: IfNotPresent
          name: server
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: "/etc/nginx/conf.d"
            name: "config"
          - mountPath: "/usr/share/nginx/html"
            name: image-repository
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        nodeSelector:
          kubernetes.io/hostname: "NODENAME"
        volumes:
        - name: config
          configMap:
            name: kvm-nginx-conf
        - hostPath:
            path: "/usr/share/libvirt/images"
          name: image-repository
- apiVersion: v1
  kind: Service
  metadata:
    name: image-repo
  spec:
    clusterIP: None
    ports:
    - name: tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      diamanti.com/app: kvm-nginx
kind: List
metadata: {}
