apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: mongo-vol-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100G
    storageClassName: high
  status:
    phase: Pending
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    labels:
      app: mongo
    name: mongo
  spec:
    replicas: 1
    selector:
      app: mongo
    template:
      metadata:
        annotations:
          diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
        creationTimestamp: null
        labels:
          app: mongo
      spec:
        containers:
        - args:
          - --wiredTigerCacheSizeGB
          - "1"
          image: mongo:3.3.6
          imagePullPolicy: IfNotPresent
          name: mongo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/db
            name: volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: mongo-vol-claim
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mongo
  spec:
    clusterIP: None
    ports:
    - name: port
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
