apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    labels:
      diamanti.com/app: ip-NODE-QOS-INDEX
    name: ip-NODE-QOS-INDEX
  spec:
    replicas: 1
    selector:
      diamanti.com/app: ip-NODE-QOS-INDEX
    template:
      metadata:
        annotations:
          diamanti.com/endpoint0: '{"network":"NET","perfTier":"QOS"}'
        creationTimestamp: null
        labels:
          diamanti.com/app: ip-NODE-QOS-INDEX
      spec:
        containers:
        - env:
          - name: RT
            value: "60000"
          - name: RW
            value: OP_TYPE
          - name: RWRPCT
            value: PER_TYPE
          - name: QD
            value: "16"
          - name: BLOCK_SIZE
            value: 16k
          image: diamanti/fio-rw:0.1
          imagePullPolicy: IfNotPresent
          name: fio
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: vol-NODE-QOS-INDEX
        - command:
          - /usr/bin/iperf3
          - -s
          image: diamanti/iperf:v0.1
          imagePullPolicy: IfNotPresent
          name: server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - sleep 60 && /usr/bin/iperf3 -M 1454 -c ip-DEST-QOS-INDEX -P 8 -t 60000
          command:
          - /bin/sh
          - -c
          image: diamanti/iperf:v0.1
          imagePullPolicy: IfNotPresent
          name: client
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/hostname: NODE
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - flexVolume:
            driver: diamanti.com/volume
            fsType: xfs
            options:
              name: vol-NODE-QOS-INDEX
              perfTier: QOS
              type: Simple
          name: vol-NODE-QOS-INDEX
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ip-NODE-QOS-INDEX
  spec:
    clusterIP: None
    ports:
    - name: tcp
      port: 5201
      protocol: TCP
      targetPort: 5201
    selector:
      diamanti.com/app: ip-NODE-QOS-INDEX
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
