apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-filesystem-delayed-provisioning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-sc-delayed-provisioning
