apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: mysql-12-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20G
    storageClassName: high
  status:
    phase: Pending
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null 
    labels:
      app: mysql-12
    name: mysql-12
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql-12
    template:
      metadata:
        annotations:
          diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
        creationTimestamp: null
        labels:
          app: mysql-12
      spec:
        containers:
        - args:
          - --datadir=/var/lib/mysql/mysql
          env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          image: mysql
          imagePullPolicy: IfNotPresent
          name: mysql
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: mysql-12-claim
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mysql-12
  spec:
    clusterIP: None
    ports:
    - name: port
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql-12
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
