apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-block-instant-provisioning
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-sc-instant-provisioning
